Include instruction data in contexts
exotic-markets/crayfish pull request #30
Opened 2024-12-08 21:35 UTC by Dodecahedr0x

Solves #24.

I chose to create a new `args` field in every context to make these context argument accessible

2024-12-09 01:15 UTC, Aursen reviewed
Seems good to me, but what will happen if the structure is directly the args structure?

2024-12-09 07:53 UTC, Aursen commented
> Solves #24 and enables pushing #22 forward.
> 
> I chose to create a new `args` field in every context to make these context arguments accessible.

It was my my goal too because you cannot work with another tuple here

2024-12-09 08:07 UTC, Dodecahedr0x commented
> Seems good to me, but what will happen if the structure is directly the args structure?

Do you mean what happens in the transfer-sol example? In this case it's available directly.

What isn't tested here though is to have multiple contexts with arguments, or using the instruction attribute along with args as handler parameters. Will add some tests cases for this

2024-12-10 12:03 UTC, Aursen requested changes

2024-12-10 12:03 UTC, Aursen commented on crates/context-macro/src/lib.rs
> +                account_struct.attrs.clear();
Here only remove the args attribute to allow flexibility

2024-12-10 12:55 UTC, Dodecahedr0x commented
Thanks for the feedback, the last commit addresses all these issues

2024-12-10 13:13 UTC, Aursen approved these changes
LFG

2024-12-10 13:13 UTC, merged